apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - ollama.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

images:
  - name: chatbot
    newName: harbor-01a.vcf.lab/bookstore/chatbot
    newTag: v20260825-517315a
