apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - ollama.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: chatbot
    newName: harbor.corp.vmbeans.com/bookstore/chatbot
    newTag: v20260219-502d206
