apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-ingress
spec:
  rules:
  - host: chatbot.apps.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatbot-service
            port:
              number: 5000
